version: '3.4'

services:
  currencychecker.web:
    image: ${DOCKER_REGISTRY-}currencycheckerweb
    build:
      context: .
      dockerfile: CurrencyChecker.Web/Dockerfile
    ports:
        - "80:80"
        - "443:443"
  currency-db:
    container_name: currency-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Alan123_"
        ACCEPT_EULA: "Y"